### ISSUE TITLE
Landing page de Urdaten en sitio web de Rich it

### ISSUE THREAD

**Issue by juanignaciocastillo** [hatshex/websiterich#21]
Hacer nueva landing de suite de soluciones de Urdaten para poner en el sitio web de Rich it. Soluciones para el sector financiero.

Mockup Miró: https://miro.com/welcomeonboard/QzRZWXV6VlZabFVQSkhhZXhrd0RiMko2Smw4bWV3OUVid2FRZWtTTGpvSkZkeHNTSUxLTHNjNXpGSHIwaHJKS3wzNDU4NzY0NTIzMTQ4NjEwMDQ5fDI=?share_link_id=360900811749

**Comment by ursula9** [comment]
Listo ya está la landing en el sitio !

<img width="1437" alt="Captura de Pantalla 2023-01-20 a la(s) 11 35 20" src="https://user-images.githubusercontent.com/7061118/213766877-314843f8-6a74-4141-a563-e5bafe2f4020.png">

**Comment by juanignaciocastillo** [comment]
Excelente Urs!!! Muchas gracias.


[image: avatar]


Juan Castillo

Gerente de Crecimiento

Wallet:  urdaten.com

Grandes corporativos:  richit.ai

Comparador de créditos:  nrich.com

Teléfono:  (+54) 9 351 6074437 <(+54)+9+351+6074437>

[image: social-icon-facebook] <https://www.facebook.com/urdaten/>

[image: social-icon-linkedin] <https://www.linkedin.com/company/urdaten/>

[image: social-icon-instagram] <https://www.instagram.com/urdaten_com/>

[image: social-icon-youtube]
<https://www.youtube.com/channel/UCj1EBWQWhxPp4VWtOJ0FmKg>

[image: social-icon-twitter] <https://twitter.com/Urdaten>
