### ISSUE TITLE
Actualización página principal Rich it con información de Urdaten

### ISSUE THREAD

**Issue by juanignaciocastillo** [hatshex/websiterich#22]
Agregar Urdaten en el home del sitio web de Rich it.

**Comment by juanignaciocastillo** [comment]
Agregar Urdaten en el home del sitio web de Rich it.

Referencia:
![actualización home rich it](https://user-images.githubusercontent.com/98432191/210644312-4fb401ee-3b3a-4c63-a3e9-cbd9997da3e2.png)

**Comment by ursula9** [comment]
Ya está listo @juanignaciocastillo 

<img width="1438" alt="Captura de Pantalla 2023-01-20 a la(s) 11 34 39" src="https://user-images.githubusercontent.com/7061118/213766581-a079f334-e866-4872-942d-e7e8d30326f6.png">

<img width="1437" alt="Captura de Pantalla 2023-01-20 a la(s) 11 35 20" src="https://user-images.githubusercontent.com/7061118/213766600-578f8db7-adef-4ed7-8eb9-eac556b931c8.png">

**Comment by juanignaciocastillo** [comment]
Quedó perfecto! Muchas gracias, excelente trabajo.


[image: avatar]


Juan Castillo

Gerente de Crecimiento

Wallet:  urdaten.com

Grandes corporativos:  richit.ai

Comparador de créditos:  nrich.com

Teléfono:  (+54) 9 351 6074437 <(+54)+9+351+6074437>

[image: social-icon-facebook] <https://www.facebook.com/urdaten/>

[image: social-icon-linkedin] <https://www.linkedin.com/company/urdaten/>

[image: social-icon-instagram] <https://www.instagram.com/urdaten_com/>

[image: social-icon-youtube]
<https://www.youtube.com/channel/UCj1EBWQWhxPp4VWtOJ0FmKg>

[image: social-icon-twitter] <https://twitter.com/Urdaten>
